language: python
dist: xenial
cache: pip

branches:
  only:
  - master
  - /^v(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/ # SemVer tags (https://github.com/semver/semver/issues/232#issuecomment-405596809)

env:
  global:
    - SKIP_GENERATE_AUTHORS=1
    - SKIP_WRITE_GIT_CHANGELOG=1
  matrix:
    WITH_CODECOV=true
before_install:
  - pip install --upgrade setuptools pip
install:
  # this is needed because polyply at the moment only works with the vermouth
  # dev version
  - pip install git+https://github.com/marrink-lab/vermouth-martinize.git#vermouth
  - pip install --upgrade .
before_script:
  - pip install --upgrade -r requirements-tests.txt
script:
  - coverage run --source=polyply $(which pytest) -vv polyply
after_success:
  - coverage report --omit='*/bin/pytest'
  - if [[ ${WITH_CODECOV} == true ]]; then codecov; fi

jobs:
  fast_finish: true
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
      env: WITH_CODECOV=false

#   - stage: docs
#     python: "3.7"
#     install:
#       - pip install --upgrade -r requirements-docs.txt
#       - pip install --upgrade .[full]
#     # script: python setup.py build_sphinx
#     script: mkdir -p doc/source/_static; sphinx-build -EnW -b html doc/source/ doc/build/html
#     after_success: skip

    - stage: pylint
      python: "3.7"
      install:
        # for now we need development version
        - pip install git+https://github.com/marrink-lab/vermouth-martinize.git#vermouth
        - pip install --upgrade -r requirements-tests.txt
        - pip install pylint
      script:
        - python run_pylint.py --disable=fixme --fail-under=8.0 polyply
        - python run_pylint.py --disable=fixme --fail-under=9.5 bin/polyply
      after_success: skip

    - stage: deploy
      python: "3.7"
      addons: skip
      env: WITH_CODECOV=false
      before_script: skip
      script: skip
      deploy:
          provider: pypi
          user: __token__
          server: https://test.pypi.org/legacy
          password:
              # travis encrypt --add deploy.password
              secure: "awerGF26dxl08ZKcKif9yQJx0BHBpCG4PYjLpqBlEiM+CbrLNn5K/oTPolhb0q1Yee8tsE+KHbw89A8FLoMCVWO3quVBWK2rK7jaibnY17XBPlPlnPkaWNKg4BIJuXUSCe7aCGf07KlolPMxQ+z51rXpP59nQ2tOEaK7seUBuMzArh+BpYvqzjWkB5FpKmOwSqRRx8jg0j1wCxwO7P0OxtEGxBq47SBSCmaCm2iU2c9tw8HELY3XJUnbqwB/7AIYai0T0ExlyhszetBLHqI8lhY8Z0ThSDcElz0CVgO2eekz6cjMdXRa12NUEGOuRaThg+eZQgbpF8hvpwz2e6J40lrygbUdz1V54ercD38XPLDv6EkvmwTyCs+RbVnX0RMjkW50qYuydHzE+qkc1TaNqhYv8idDgYdcF3HgE32xxmOmxU8wLCt9cEfvT4hAT+TW0B0/0Jzj03h3lGSd4PlL5KOjZggqfxLgFgdbfS10TsygxQm0d/+/8m9Rck2AP/DVNqK2mZaONZUWWZCctkM5KuEKAtCyWBQVnNIJleEsNOe5JA3F0c3pFhi/43XpBg3w8UH1wMzDRRbxr+YJpTkXURh+V9XgfgcU1/xSsB5Qqk7FK8ca18JsdDEEjw7n4TfBso18bJD/SVC/XOt7zqZ+xnieFX6US8TJUChdWRuF2nM="
          on:
              tags: true
